### PR TITLE
Add an OEP-2 compliant openedx.yaml file

### PR DESCRIPTION
**Pull request by cpennington**
This adds an `openedx.yaml` file, as described by OEP-2:
http://open-edx-proposals.readthedocs.io/en/latest/oeps/oep-0002.html

The data in this file was transformed from the contents of
edx/repo-tools-data:repos.yaml

### CODE REVIEW

**Comment by cpennington** [comment]
@pmitros: Just pinging you to let you know that this PR will mark you as the owner of this repo.

**Comment by pmitros** [comment]
@cpennington Okay. 

Any action needed on my part?

It'll be interesting to be an owner without commit access :)

**Comment by cpennington** [comment]
How'd you manage to not have commit access? Isn't this your code? I'm very confused.

**Comment by cpennington** [comment]
Alright, I gave `edx/push-pull-all` write access to the repo, so you should have access now.

**Comment by cpennington** [comment]
No action needed right now, otherwise.

**Pull request merged**
